ci: add a new release workflow
DelineaXPM/ansible-core-collection pull request #44
Opened 2023-03-15 17:12 UTC by andrii-zakurenyi

:thinking:

2023-03-15 17:17 UTC, andrii-zakurenyi commented
Less than a hundred lines of logs for that "build-and-publish" step. Charming :sparkles:

2023-03-15 17:18 UTC, andrii-zakurenyi commented
Not sure what should be the trigger of this workflow though

2023-03-15 17:27 UTC, andrii-zakurenyi commented
Will it be good enough? :man_shrugging: 

```yaml
on:
  push:
    tags:
      - v*
```

2023-03-15 17:45 UTC, tdillenbeck commented on .github/workflows/release.yaml
> +  push:
I don't know all the context, but this seems right to me.

2023-03-15 17:45 UTC, tdillenbeck approved these changes

2023-03-15 18:13 UTC, sheldonhull requested changes
The release command should be in Mage. It could run the release plus create the github release commands which actually would tag. Let me look today and I’ll provide review feedback. You won’t use pull request  on trigger.

2023-03-15 22:22 UTC, sheldonhull commented
@andrii-zakurenyi included some other tasks to help with this, as ideally you can run locally the same as remote. These changes include:

- install just a single venv for running publishing commands.
- using that venv (not super important in CI, but ideal for local). 
- using semver bump and `yq` bump the galaxy yaml version as part of development.


I'm ok merging this as is now to break things into smaller pieces, but there's one last thing to look at afterward... does `ansible-galaxy` publishing actually create a github release? If not then we can either look at using the github action that does the build and workflow creation, OR we add a github release via `gh release create` invocation to the mage release process that uses the semver bump. `gh release` actually adds the tag for us so we don't push manual tags anymore. Makes it nice for the release logs. 

Almost no github repos get manual tags due to this github release tag creation process.

2023-03-18 01:18 UTC, sheldonhull commented
flipped to draft as `do-not-merge` is not a blocking condition. I'll catch up next week with you and if you want to pair on anything to wrap it up just let me know. Cheers

2023-03-21 19:33 UTC, sheldonhull commented
Haven't forgotten about this. Will review soon as lots of changes and want to observe the improvements you made.  Cheers

2023-03-22 16:20 UTC, sheldonhull commented
Merging. Will handle further review or changes for docs in a different PR. Thank you for this hard work @andrii-zakurenyi

2023-03-22 20:51 UTC, merged